- name: install and start service
  hosts: appfw-rhel8
  vars:
    service:
      web:
        package: httpd
        state: started
  tasks:
  - name: install webserver apache
    yum:
      name: httpd
      state: latest
      enabled: yes
  - name: start service {{ service.web.package }}
    service:
      name: "{{service.web.package}}"
      state: "{{service.web.state}}"
  - name: add to firewalld
    firewalld:
      name: http
      state: enabled
      permanent: yes
  - name: reload firewalld
    service:
      name: firewalld
      state: restarted