- name: install package by with_items
  hosts: appfw-rhel8
  become: true

  tasks:
  - name: install packages
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - nano
      - vim
      - samba